/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diagnose;


import config.PanelPrinter;
import javax.swing.JPanel;


/**
 *
 * @author PC11
 */
public class DiagnosePrinting extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public DiagnosePrinting() {
        initComponents();
        
    }
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_page = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pat_id = new javax.swing.JTextField();
        p_name = new javax.swing.JTextField();
        sym = new javax.swing.JTextField();
        stat = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        treat = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_page.setBackground(new java.awt.Color(255, 255, 255));
        p_page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ST. CECILIA'S COLLEGE - CEBU, INC.");
        p_page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 40, 400, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Poblacion Ward II, Minglanilla Cebu");
        p_page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 68, 400, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        p_page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 590, 17));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Patient ID:");
        p_page.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Patient Name:");
        p_page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Symptom:");
        p_page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 100, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Status:");
        p_page.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 100, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Date:");
        p_page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 100, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Treatment:");
        p_page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 100, 30));

        pat_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(pat_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, 30));

        p_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, 30));

        sym.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(sym, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 220, 30));

        stat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 220, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 220, 30));

        treat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p_page.add(treat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 220, 30));

        print.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        p_page.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 90, 40));

        jPanel1.add(p_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 630, 620));

        jLabel1.setBackground(new java.awt.Color(0, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 100, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 760, 787));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    printDiagnose pd = new printDiagnose();   
    pd.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
     JPanel myPanel = new JPanel();
     PanelPrinter pPrint = new PanelPrinter(p_page);
     pPrint.printPanel();
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosePrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosePrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosePrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosePrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiagnosePrinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField p_name;
    private javax.swing.JPanel p_page;
    public javax.swing.JTextField pat_id;
    private javax.swing.JButton print;
    public javax.swing.JTextField stat;
    public javax.swing.JTextField sym;
    public javax.swing.JTextField treat;
    // End of variables declaration//GEN-END:variables
}
